//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooShop.FolderEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int idAnimal { get; set; }
        public string nameAnimal { get; set; }
        public int placeAnimalID { get; set; }
        public int typeOfAnimalID { get; set; }
        public byte[] photoPreview { get; set; }
        public string description { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual TypeOfAnimal TypeOfAnimal { get; set; }
    }
}
