//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooShop.FolderEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZooShopEntities : DbContext
    {
        public ZooShopEntities()
            : base("name=ZooShopEntities")
        {
        }

        public static ZooShopEntities context;

        public static ZooShopEntities GetContext()
        {
            if (context == null)
                context = new ZooShopEntities();
            return context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfAnimal> TypeOfAnimal { get; set; }
    }
}
